### ISSUE TITLE
Doesnt install on omv 3.0.74

### ISSUE THREAD

**Issue by DmitryNefedov** [OpenMediaVault-Plugin-Developers/openmediavault-virtualbox#13]
fresh omv 3.0.74 install with omv-update.
Install omv-extras
Virtual box installation fails
`
The following packages have unmet dependencies:
 openmediavault-virtualbox : Depends: build-essential but it is not installable
                             Depends: linux-headers-686-pae but it is not installable or
                                      linux-headers-amd64 but it is not going to be installed
                             Depends: makepasswd but it is not installable
                             Depends: phpvirtualbox but it is not going to be installed
                             Depends: virtualbox but it is not going to be installed
                             Depends: virtualbox-ext-pack but it is not installable or
                                      virtualbox-ext-pack-installer but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by ryecoaaron** [comment]
I'm guessing you don't have the 686 kernel installed?  What is the output of: uname -a
