### ISSUE TITLE
add vbox user to some default groups

### ISSUE THREAD

**Issue by raulfg3** [OpenMediaVault-Plugin-Developers/openmediavault-virtualbox#5]
Can you please add vbox user to cdrom & users groups so you can do install on VM from CD and share VM by SAMBA?.

I comment my experience on this post:

http://forums.openmediavault.org/index.php/Thread/9017-error-in-phpvirtualbox-acessing-sr0/?postID=83106#post83106

Thanks.

**Comment by nohatssir** [comment]
No. We can't blindly add system users to groups. That would be wrong of us to do. The system administrator should be doing that.

**Comment by raulfg3** [comment]
ok, no problem , if others users have same problem, they can apply same
trick that I use  on my side.


Please close my open bug, and sorry for open it.



2015-06-24 20:23 GMT+02:00 nohatssir <notifications@github.com>:

> No. We can't blindly add system users to groups. That would be wrong of us
> to do. The system administrator should be doing that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-virtualbox/issues/5#issuecomment-114970931>
> .
>



-- 
Raul Fernandez García

   raulfg3@gmail.com

**Comment by nohatssir** [comment]
No problem! Your contribution is appreciated!

**Comment by ryecoaaron** [comment]
I personally think adding the vbox user to the cdrom group would be a good idea.  Adding to the users group is a bad idea in my opinion.

**Comment by nohatssir** [comment]
I'm not completely against the cdrom group since it can't cause much trouble (I hope?). If you feel like it's a good idea feel free to go ahead. :)

**Comment by ryecoaaron** [comment]
I think I will.  I use it quite a bit when I get a driver disc or something I don't feel like making an ISO of.
