### ISSUE TITLE
No OMV WebUI

### ISSUE THREAD

**Issue by br41n86** [OpenMediaVault-Plugin-Developers/openmediavault-virtualbox#8]
After installing openmediavault-virtualbox i am unable to access the WebUI from OMV 3.0.
After purging the plugin everything works again.

**Comment by ryecoaaron** [comment]
The plugin hasn't been finished for OMV 3.x.

**Comment by br41n86** [comment]
Ok, i thought it is ready to be tested because of last commit.
In the changelog it says stable. Is there anything i can help with?
Would like to help speed up the plugin adapting to OMV 3.0.

**Comment by ryecoaaron** [comment]
I would release the package into the repo if it were stable.  Never assume code on github is stable.

We are going to switch to using virtualbox from the debian repos.  4.3 is in jessie stable and 5.0 is jessie backports.  So, that will change the dependencies right away.  Upgrades won't be possible without purging previous installs.  Need to build multiple packages of phpvirtualbox and virtualbox-extpack-installer with dependency on specific version to go with each version available.

I'm not even running OMV 3.0.  Why are you?

**Comment by br41n86** [comment]
No, i am not. I am only testing it on my VBox under Windows.
So i can check, if everything i need is already working before i upgrade.

**Comment by br41n86** [comment]
For the repo thing, wouldn't it be better to use the jessie repo from virtualbox itself?
deb http://download.virtualbox.org/virtualbox/debian jessie contrib

**Comment by ryecoaaron** [comment]
We used to.  Too many issues.  That is why we started mirroring it on omv-extras.  We always wanted to use debian repo but version was too old.  Not an issue with jessie anymore.

**Comment by nohatssir** [comment]
The Nginx config has been updated to fix this issue.
